### ISSUE TITLE
Set meta data using \tnset or \metadataset

### ISSUE THREAD

**Issue by cmhughes** [rbrignall/OU-SUPPS#25]
Hi Robert,
I'm writing this issue mainly in relation to `outn.cls` and `ouab.cls` but I think it might relate to the other classes in the bundle as well.

At present, the preambles of tutor notes and assignment booklets consist of commands such as:

```
\faculty{Faculty of Science, Technology, Engineering and Mathematics}
\modulecode{MST125}
\moduletitle{Essential mathematics 2}
\abtitle{TMA 02}
\abyear{2017J}
\copyrightyear{2017}
\suppno{WEB 05181 2}
\versionno{6.1}
```

I wonder if you would like to see an option so that, for example, the following could be used:

```
\metadataset = {faculty={Faculty of Science, Technology, Engineering and Mathematics},
                          module code = {MST125},
                          module title={Essential mathematics 2},
                          title = {TMA 02},
                          year = {2017J},
                          copyright year = {2017},
                           supp no = {WEB 05181 2},
                           version no = {6.1}
}
```

In relation to https://github.com/rbrignall/OU-SUPPS/pull/24, we might be able to say, for example:

```
\metadataset = {tutor only title={something},
                           student only title={something else},
}
```

I don't think that there would be a need to remove the existing commands -- the above set up would be an *option*, not a requirement.

Not sure what you think about this -- all feedback/ideas very welcome! :) 
Best
Chris

**Comment by rbrignall** [comment]
I like this, providing the class files don't get too massively complicated: maybe ensure the code is developed as a distinct block within `outn.cls` so it's clear that it acts on top of the basic method interaction.

One major comment: If we do this, we should do it to all the class files simultaneously. Taking that into account, can we do this as part of a v1.0 major release? I presume it shouldn't take too long to develop.

Robert

**Comment by cmhughes** [comment]
This was implemented at https://github.com/rbrignall/OU-SUPPS/pull/32
