### ISSUE TITLE
outn: `\mk[text]{}` throws error

### ISSUE THREAD

**Issue by rbrignall** [rbrignall/OU-SUPPS#26]
@cmhughes: Passing an empty command to the \mk command, e.g. to produce a comment without an associated mark, throws a `Missing number, treated as zero` error.

This can be avoided by using  `\mk[text]{\relax}` in the tex file, but looks like `\@update@totals` could do with tweaking.

**Comment by cmhughes** [comment]
Thanks for catching this, and apologies for the bug -- I'll submit a fix within the next few days.

Best
Chris
