### ISSUE TITLE
Bug in metadataset for exam instructions (and the other .cls)

### ISSUE THREAD

**Issue by cmhughes** [rbrignall/OU-SUPPS#38]
I'm putting this here, just so that we can keep track of it.

Consider the following minimum file
```
\documentclass{ouexam} 
\metadataset{
            module code=MST124,
            session=C,
            module title=Title of Module,
            exam code=MST1241706F1PV1,
            exam time={10:00\,am -- 1:00\,pm},
            exam day=Tuesday 7,
            exam month=October,
            exam year=2016,
            time allowed=3 hours,
            copyright year=2016,
            instructions={\textbf{instructions}},
            }
\begin{document}
\maketitle
\end{document}
```
This throws the error
```
! Argument of \reserved@a has an extra }.
<inserted text> 
                \par 
l.14             }
```
With reference to https://tex.stackexchange.com/questions/324956/pgfkeys-estore-in-handler-does-not-work-as-expected this can be fixed by changing `ouexam.cls` to contain:
```
instructions/.store in=\@examinstructions
```
----
As a side note: I think this highlights further desire to have a `test-case` directory, that contains a batch of dedicated test case files to explore all of the different features that have been developed. The test-cases could be compiled and tracked every time features are edited, added or removed. How does this sound to you, Robert? Would you prefer it to be a separate repository, or would you be ok with it living here in, say, a `test-case` directory? If it sounds ok, I'll submit a pull request with a few test-cases which can be added to as and when we wish to test different features and/or combination of switches/commands/etc.

**Comment by rbrignall** [comment]
Hi,
Thanks for the bug report: can this pgfkeys fix be implemented immediately? Seems like something we should fix before the major release.

As for test-case: yes, I think this is a good idea (folder in the repository is ok for now, though we might think about a separate repository in due course). However, right now we need to get this major release out asap.

**Comment by cmhughes** [comment]
I'll try to get to this over the weekend (25th/26th November, 2017).

**Comment by cmhughes** [comment]
Resolved as of https://github.com/rbrignall/OU-SUPPS/pull/40
