### ISSUE TITLE
Ability to nudge (vertically) the total/total*/subtotal/subtotal* horizontal lines

### ISSUE THREAD

**Issue by cmhughes** [rbrignall/OU-SUPPS#43]
I spoke with I.S at the school meeting in December, and he said that he would like the ability to nudge vertically the total/total*/subtotal/subtotal* commands in `outn.cls`. 

Perhaps the commands could be updated to take a third optional argument that details a vertical spacing to be applied...?

**Comment by rbrignall** [comment]
General comment on this one: behaviour of those rules in general seems to be a bit unpredictable. Sometimes they appear quite a bit below the (e.g.) "Subtotal" margin text, and other times they align nicely.

**Comment by rbrignall** [comment]
Inconsistent spacing issue has now been fixed so `\total` etc are now a consistent space above their rule irrespective of the content of the previous paragraph.

I can add an optional 3rd parameter, but I'm unclear what behaviour we want it to have -- is it to increase the space between the (e.g.) "total" text and the rule?
