### ISSUE TITLE
Possible "check" option for ouab

### ISSUE THREAD

**Issue by cmhughes** [rbrignall/OU-SUPPS#52]
For `ouab.cls` we currently have the `\question` command which has the form `\question{<number of marks>}`.

I'd like to explore passing an option to the `documentclass` in the form (of something like) `\documentclass[check]` so that it outputs some kind of text following each question that validates that total of the `\mk` commands (and friends) adds up to the value passed to the `\question` command. 

It might look like, for example:
```
Question 3 total: 10 marks
Total marks specified: 10 marks
```
It could be coded to give a warning, perhaps in red, if the two things don't tally.

Instead of a new option, perhaps it could be tied to the `draft` option...?

**Comment by rbrignall** [comment]
Note: This is already experimentally implemented via the "markcheck" option.

I've created the ouab-markcheck branch off develop to investigate revising this to make it more fully supported.
