### ISSUE TITLE
Possibly renaming of master branch to main

### ISSUE THREAD

**Issue by cmhughes** [rbrignall/OU-SUPPS#75]
Hi Robert,
I was recently made aware of github's move away from using the name `master` as the main branch; see, for example, [https://github.com/github/renaming](https://github.com/github/renaming). 

The link I've provided gives details of how to rename the `master` branch; I've followed these instructions on one of my github projects, and it worked fine without issue. 

I thought I'd raise this, just in case it's helpful.

Best wishes
Chris

**Comment by rbrignall** [comment]
Done!
