### ISSUE TITLE
outn: \mk[comment]{} throws error

### ISSUE THREAD

**Issue by rbrignall** [rbrignall/OU-SUPPS#99]
Can't use \mk command without a second parameter.

(Workarounds are to use \mk*[comment]{}, or \mk[comment]{\relax}.)

**Comment by cmhughes** [comment]
This seems like expected behaviour...? Referencing the documentation
```tex
\mk[⟨description⟩]{⟨n⟩}[⟨voffset⟩]
\mk*[⟨description⟩]{⟨n⟩}[⟨voffset⟩]
```
so the
* `*` is optional
* [`#1`] is optional
* {`#2`} is _mandatory_
* [`#3`] is optional

**Comment by rbrignall** [comment]
Yes, I agree, although some users tend to think of empty braces `\mk{}` as being a legitimate specification of the mandatory parameter, and indeed some bits of LaTeX use it as such (`\setbeamertemplate{navigation symbols}{}` springs to mind).

I wouldn't anticipate doing anything more than appending/prepending `\relax`, but of course it mustn't break the auto-adding-up.
